<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AfipSdkBillingExampleDotnet</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Afip.Net" Version="1.1.2" />
  </ItemGroup>
</Project>
